### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by volehuy1998** [amate/VideoConvertStreamServer#1]
I tried inject to Microsoft Powerpoint but nothing happen.
Can you commit tutorial/guide that how to use this DLL?

**Comment by amate** [comment]
This is a video streaming server.
Powerpoint is not supported.

**Comment by volehuy1998** [comment]
> This is a video streaming server. Powerpoint is not supported.

Sorry, I tried comment into hack dialog of your repository.
